add_subdirectory(RandomTextureCubeScene)
add_subdirectory(Simple2DScene)
add_subdirectory(SkyboxScene)
add_subdirectory(RotationScene)
add_subdirectory(TreeTransformScene)
add_subdirectory(SoundScene)
add_subdirectory(TextScene)
add_subdirectory(ScreenSaverScene)
add_subdirectory(LightingScene)
add_subdirectory(GeometryShaderScene)
add_subdirectory(BlendScene)
add_subdirectory(AnimationScene)
add_subdirectory(PostProcessingScene)
add_subdirectory(MirrorScene)
add_subdirectory(CollisionScene)